spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        max-page-size: 100
server:
  servlet:
    context-path: /api
